version: '2'
services:
    dns:
        restart: always
        image: axxyhtrx/ntpd
        volumes:
            - ./ntpd.conf:/etc/ntpd.conf
        ports:
            - "123:123/udp"
        cap_add:
            - NET_ADMIN
            - SYS_TIME
